spring.datasource.url=jdbc:postgresql://localhost:5433/frauddb
spring.datasource.username=frauduser
spring.datasource.password=fraudpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=8081